language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
  - "iojs-v1"
  - "iojs-v2"
env:
  - SUITE=smoke
  - SUITE=unit
  - SUITE=integration
  - SUITE=lint
services:
  - memcached
  - mongodb
  - mysql
  - redis
  - cassandra
  - postgres
before_install:
  - sudo apt-get install -qq time
  - make update_npm_global
  - if [ "$SUITE" = "integration" ]; then make sub_node_modules; fi
install: if [ "$SUITE" != "smoke" ]; then npm install; fi
script: make $SUITE
