name: Create Release

# Manual trigger only
on: [workflow_dispatch]

jobs:
  tag-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1 # https://github.com/actions/setup-node
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      run: npm ci
    - name: Setup GitHub Credentials
      run: |
        git config user.name $GITHUB_ACTOR
        git config user.email gh-actions-${GITHUB_ACTOR}@github.com
    - name: Create Release tag
      run: node ./bin/create-release-tag.js --branch ${{ github.ref }} --repo-owner ${{ github.repository_owner }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Get Created Tag
      id: get_tag
      run: echo "::set-output name=latest_tag::$(git describe --tags --abbrev=0)"
    - name: Create GitHub Release
      run: node ./bin/create-github-release.js --tag ${{ steps.get_tag.outputs.latest_tag }} --repo-owner ${{ github.repository_owner }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish API Docs
      run: npm run publish-docs
    - name: Update system configuration pages
      env:
        VERSION: ${{ steps.get_tag.outputs.latest_tag}}
      run: |
        # Need to strip the v from version(i.e. - v8.6.0 is not 8.6.0)
        PKG_VERSION="${VERSION//v/}""
        PAYLOAD="{
             \"system_configuration\": {
               \"key\":   \"nodejs_agent_version\",
               \"value\": \"$PKG_VERSION\"
            }
          }"
        CONTENT_TYPE='Content-Type: application/json'
        # STAGING
        curl -X POST 'https://staging-api.monisagent.com/v2/system_configuration.json' \
          -H "X-Api-Key:${{ secrets.NEW_RELIC_API_KEY_STAGING }}" -i \
          -H "$CONTENT_TYPE" \
          -d "$PAYLOAD"
        # PRODUCTION
        curl -X POST 'https://api.monisagent.com/v2/system_configuration.json' \
          -H "X-Api-Key:${{ secrets.NEW_RELIC_API_KEY_PRODUCTION }}" -i \
          -H "$CONTENT_TYPE" \
          -d "$PAYLOAD"
        # EU PRODUCTION
        curl -X POST 'https://api.eu.monisagent.com/v2/system_configuration.json' \
          -H "X-Api-Key:$ {{ secrets.NEW_RELIC_API_KEY_EU }}" -i \
          -H "$CONTENT_TYPE" \
          -d "$PAYLOAD"
